---
title: "VJ_gene_analysis"
author: "GaryWang"
date: "9/29/2021"
output: html_document
---

```{r setup, include=FALSE,cache = TRUE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'Y:/Files/JHU/Labs/Git_Repos/COVID19_Cross_Reference')
```
Load libraries
```{r, include=FALSE, warning = FALSE}
library(dplyr)
library(Seurat)
library(stringr)
library(tidyr)
library(patchwork)
library(pheatmap)
library(readxl)
library(immunarch)
library(circlize)
library(networkD3)
library(htmlwidgets)
```

```{r}
Shared_Surface_TCR<-read.csv('Y:/Files/JHU/Labs/Git_Repos/COVID19_Cross_Reference/Data/Output/M1_Common_Surface.csv')
```
# Plot VJ-genes Usage
First calculate a VJ adjacency matrix
```{r}
Shared_Surface_TCR[Shared_Surface_TCR==""] <-"N.A." 
V_list<-unique(Shared_Surface_TCR$V)
J_list<-unique(Shared_Surface_TCR$J)
ad_mtx<-matrix(0,length(V_list),length(J_list)) #Rows-->V; Columns-->J
rownames(ad_mtx)<-V_list
colnames(ad_mtx)<-J_list
for (vgene in V_list) {
  for (jgene in J_list) {
    temp_df<-filter(Shared_Surface_TCR,V ==vgene & J == jgene)
    ad_mtx[vgene,jgene] <-nrow(temp_df)
  }
}
```
To plot chord diagrams, we can generate a uniform color vector for the V/J genes.
```{r}
VJ_genes<-c(V_list,J_list)
col_VJ<-rand_color( length(VJ_genes),luminosity = 'dark')
names(col_VJ)<-VJ_genes
```
Plot chord diagram
```{r, message=F}
png(file = "VJ_Usage.png", width = 1800, height = 1800)
  par(mar=c(3,3,4,0))
  grid_col <- col_VJ[c(rownames(ad_mtx),colnames(ad_mtx))] 
  chordDiagram(ad_mtx,
               annotationTrack = "grid",
              # big.gap = 10,
               preAllocateTracks = 2,
               grid.col = grid_col)
    
  circos.trackPlotRegion(
    track.index = 1,
    panel.fun = function(x, y) {
      xlim = get.cell.meta.data("xlim")
      ylim = get.cell.meta.data("ylim")
      sector.name = get.cell.meta.data("sector.index")
      circos.text(
        mean(xlim),
        ylim[1] - 1,
        sector.name,
        facing = "clockwise",
        niceFacing = TRUE,
        adj = c(0, 0.5),
        col = "#444541",
        cex = 2
      )
    },
    bg.border = NA
  )
  title(main = list("VJ Gene Usage--331 Cross-Reactive TCRs to \n SARS-CoV2 Spike Protein and M1",cex = 4), outer = F, line = -6)
  abline(h = 0.02, lty = 2, col = "#00000080",lwd = 2)
  circos.clear()
  dev.off()
```

